# Servidor HTTP
server:
  port: 7777

# Spring
spring:
  application:
    name: service-registry

# Eureka
eureka:
  client:
    eurekaServerReadTimeoutSeconds: 40
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    useDnsForFetchingServiceUrls: true
    leaseExpirationDurationInSeconds: 3
    hostname: localhost
    preferIpAddress: false
