# Servidor HTTP
server:
  port: 8080

# Spring
spring:
  application:
    name: turbine-server

# Turbine
turbine:
  aggregator:
    clusterConfig: HYSTRIX-SERVER
  appConfig: HYSTRIX-SERVER

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
