# Servidor HTTP
server:
  port: 8888

encrypt:
  key: key

management:
  security:
    enabled: false

# Propriedades do Spring
spring:
  application:
     name: cloud-configuration
  cloud:
    config:
      server:
        monitor:
          github:
            enabled: true
        git:
          uri: https://github.com/andersonlfeitosa/spring-cloud-configuration-files.git
          basedir: /tmp/spring-cloud-configuration-files
  rabbitmq:
    host: localhost
    port: 5672
